# Pre Work Part 2
# NumPy
math in a more advanced way

In [1]:
#imports
import numpy as np

## Numpy's four specials

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


## Array

In [3]:
vec=np.array([[1,2,3],[4,5,6],[23,8,11]])
print(vec)
mat=np.array([[1,2,1],[4,5,9],[1,8,9]])
print('#-------------------------------break------------------------------------------------#')
print(mat)
print('#-------------------------------break------------------------------------------------#')
print(mat.T)

[[ 1  2  3]
 [ 4  5  6]
 [23  8 11]]
#-------------------------------break------------------------------------------------#
[[1 2 1]
 [4 5 9]
 [1 8 9]]
#-------------------------------break------------------------------------------------#
[[1 4 1]
 [2 5 8]
 [1 9 9]]


## Array+Range=Arange

In [4]:
vec2=np.arange(0,20)
print(vec2)
numpyarangey1=np.arange(3,22,16)
print(numpyarangey1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 3 19]


## Linspace and reshape

In [5]:
vec4=np.linspace(0,5,10)
print(vec4)
print(vec4.reshape(5,2))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


## Zeros and ones and eyes

In [6]:
matzeros1=np.zeros([5,3])
print(matzeros1)
print('#-------------------------------break------------------------------------------------#')
matones1=np.ones([3,4])
print(matones1)
print('#-------------------------------break------------------------------------------------#')
mateye1=np.eye(5)
print(mateye1)
print('#-------------------------------break------------------------------------------------#')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
#-------------------------------break------------------------------------------------#
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
#-------------------------------break------------------------------------------------#
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
#-------------------------------break------------------------------------------------#


## Add, multiply, divide and square root of arange

In [7]:
vec5=np.arange(3,8)
vec6=np.arange(1,6)
print(vec5)
print('#-------------------------------break------------------------------------------------#')
print(vec6)
print('#-------------------------------break------------------------------------------------#')
print(vec5+vec6)
print('#-------------------------------break------------------------------------------------#')
print(vec5*vec6)
print('#-------------------------------break------------------------------------------------#')
print(1/vec5)
print('#-------------------------------break------------------------------------------------#')
print(np.sqrt(vec5*vec6))
print('#-------------------------------break------------------------------------------------#')

[3 4 5 6 7]
#-------------------------------break------------------------------------------------#
[1 2 3 4 5]
#-------------------------------break------------------------------------------------#
[ 4  6  8 10 12]
#-------------------------------break------------------------------------------------#
[ 3  8 15 24 35]
#-------------------------------break------------------------------------------------#
[0.33333333 0.25       0.2        0.16666667 0.14285714]
#-------------------------------break------------------------------------------------#
[1.73205081 2.82842712 3.87298335 4.89897949 5.91607978]
#-------------------------------break------------------------------------------------#


## MatMul(Matrix Multiplication)

In [8]:
print(mat)
print('#-------------------------------break------------------------------------------------#')
print(vec)
print('#-------------------------------break------------------------------------------------#')
product=np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]
#-------------------------------break------------------------------------------------#
[[ 1  2  3]
 [ 4  5  6]
 [23  8 11]]
#-------------------------------break------------------------------------------------#
[[ 32  20  26]
 [231 105 141]
 [240 114 150]]


## Linalg

In [9]:
print(np.linalg.solve(mat,product))
print('#-------------------------------break------------------------------------------------#')
print(np.linalg.inv(mat))

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [23.  8. 11.]]
#-------------------------------break------------------------------------------------#
[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


## Finding the unique values in an array

In [10]:
vec7=np.array(['blue','green','red','Red','orange','purple','white','black','purple',6])
print(vec7)
print('#-------------------------------break------------------------------------------------#')
print(np.unique(vec7))

['blue' 'green' 'red' 'Red' 'orange' 'purple' 'white' 'black' 'purple' '6']
#-------------------------------break------------------------------------------------#
['6' 'Red' 'black' 'blue' 'green' 'orange' 'purple' 'red' 'white']


## Random
```
random.rand
random.randn
```

In [11]:
random_mat=np.random.rand(5,5)
print(random_mat)
print('#-------------------------------break------------------------------------------------#')
rand_mat1=np.random.randn(10,5)
print(rand_mat1)

[[0.98808995 0.88529284 0.72770628 0.48134232 0.60288724]
 [0.61035437 0.83916725 0.64739773 0.94330146 0.06638919]
 [0.2432535  0.45975662 0.38832284 0.6786458  0.89015808]
 [0.1046693  0.55070737 0.98901635 0.96135628 0.3349504 ]
 [0.29321803 0.52069268 0.81303998 0.91840361 0.98669848]]
#-------------------------------break------------------------------------------------#
[[-1.62844806 -0.23799444  0.34990101 -0.23961323 -0.4293945 ]
 [ 2.69667929  0.57138983  0.7458118  -0.68234772 -0.92429809]
 [-1.24169843 -1.45395993 -0.8664597  -0.68778081 -0.86579835]
 [-1.07455972  1.01993955 -1.31048201  0.23128028 -0.20736838]
 [ 0.07021259  0.24831603  1.42263999  0.96738743  0.31780564]
 [-2.1004002   0.22979531  1.53062773  0.71230721  0.0422116 ]
 [-0.97583063  0.64105514 -0.21022044  0.52961954  0.8503158 ]
 [-1.44799996  1.0187636  -0.11990523  0.06173182  0.54310262]
 [-2.00163302 -0.30058876 -1.05312314  0.45041293 -0.59322718]
 [ 0.36024595 -0.54188599 -0.00347775  0.39264959 -0.36

## Mean and Standard Deviation

In [12]:
print(np.mean(rand_mat1))
print(np.std(random_mat))

-0.11114470618853113
0.2806503656006477


## Minimum and Maximum

In [13]:
print(np.min(random_mat))
print(np.max(random_mat))

0.06638919461710957
0.9890163468513492


## Random Vectors

In [14]:
rand_vec1=np.random.randn(19)
print(rand_vec1)
print('#-------------------------------break------------------------------------------------#')
print(rand_vec1[6])
print('#-------------------------------break------------------------------------------------#')
print(rand_vec1[4:9])

[ 2.24249213  1.25892355 -1.3739998  -0.19145228 -1.08014024  0.19455146
 -1.06580306 -1.47127565 -0.27287145  0.24278876 -1.02221927 -0.34232022
 -1.22974044 -0.1367791  -0.82647291 -1.66154358  0.07160188 -0.44131776
 -1.19638482]
#-------------------------------break------------------------------------------------#
-1.0658030559537792
#-------------------------------break------------------------------------------------#
[-1.08014024  0.19455146 -1.06580306 -1.47127565 -0.27287145]


## Non Consecutive entries in np.arange

In [15]:
print(np.arange(0,15,3))
print(rand_vec1[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 2.24249213 -0.19145228 -1.06580306  0.24278876 -1.22974044]


## Specific components

In [16]:
print(rand_mat1)
print(rand_mat1[1][2])
print(rand_mat1[1,2])

[[-1.62844806 -0.23799444  0.34990101 -0.23961323 -0.4293945 ]
 [ 2.69667929  0.57138983  0.7458118  -0.68234772 -0.92429809]
 [-1.24169843 -1.45395993 -0.8664597  -0.68778081 -0.86579835]
 [-1.07455972  1.01993955 -1.31048201  0.23128028 -0.20736838]
 [ 0.07021259  0.24831603  1.42263999  0.96738743  0.31780564]
 [-2.1004002   0.22979531  1.53062773  0.71230721  0.0422116 ]
 [-0.97583063  0.64105514 -0.21022044  0.52961954  0.8503158 ]
 [-1.44799996  1.0187636  -0.11990523  0.06173182  0.54310262]
 [-2.00163302 -0.30058876 -1.05312314  0.45041293 -0.59322718]
 [ 0.36024595 -0.54188599 -0.00347775  0.39264959 -0.36294193]]
0.7458118026462501
0.7458118026462501


## Two specific components

In [17]:
print(rand_mat1[0:2,1:3])

[[-0.23799444  0.34990101]
 [ 0.57138983  0.7458118 ]]


## Changing some values in an array(vector)

In [18]:
print(rand_vec1)
print('#-------------------------------break------------------------------------------------#')
rand_vec1[3:5]=4
print('#-------------------------------break------------------------------------------------#')
print(rand_vec1)
print('#-------------------------------break------------------------------------------------#')
rand_vec1[3:5]=[1,2]
print('#-------------------------------break------------------------------------------------#')
print(rand_vec1)

[ 2.24249213  1.25892355 -1.3739998  -0.19145228 -1.08014024  0.19455146
 -1.06580306 -1.47127565 -0.27287145  0.24278876 -1.02221927 -0.34232022
 -1.22974044 -0.1367791  -0.82647291 -1.66154358  0.07160188 -0.44131776
 -1.19638482]
#-------------------------------break------------------------------------------------#
#-------------------------------break------------------------------------------------#
[ 2.24249213  1.25892355 -1.3739998   4.          4.          0.19455146
 -1.06580306 -1.47127565 -0.27287145  0.24278876 -1.02221927 -0.34232022
 -1.22974044 -0.1367791  -0.82647291 -1.66154358  0.07160188 -0.44131776
 -1.19638482]
#-------------------------------break------------------------------------------------#
#-------------------------------break------------------------------------------------#
[ 2.24249213  1.25892355 -1.3739998   1.          2.          0.19455146
 -1.06580306 -1.47127565 -0.27287145  0.24278876 -1.02221927 -0.34232022
 -1.22974044 -0.1367791  -0.82647291 -1.

In [19]:
print(rand_mat1)
print('#-------------------------------break------------------------------------------------#')
rand_mat1[1:3,3:5]=0
print('#-------------------------------break------------------------------------------------#')
print(rand_mat1)

[[-1.62844806 -0.23799444  0.34990101 -0.23961323 -0.4293945 ]
 [ 2.69667929  0.57138983  0.7458118  -0.68234772 -0.92429809]
 [-1.24169843 -1.45395993 -0.8664597  -0.68778081 -0.86579835]
 [-1.07455972  1.01993955 -1.31048201  0.23128028 -0.20736838]
 [ 0.07021259  0.24831603  1.42263999  0.96738743  0.31780564]
 [-2.1004002   0.22979531  1.53062773  0.71230721  0.0422116 ]
 [-0.97583063  0.64105514 -0.21022044  0.52961954  0.8503158 ]
 [-1.44799996  1.0187636  -0.11990523  0.06173182  0.54310262]
 [-2.00163302 -0.30058876 -1.05312314  0.45041293 -0.59322718]
 [ 0.36024595 -0.54188599 -0.00347775  0.39264959 -0.36294193]]
#-------------------------------break------------------------------------------------#
#-------------------------------break------------------------------------------------#
[[-1.62844806 -0.23799444  0.34990101 -0.23961323 -0.4293945 ]
 [ 2.69667929  0.57138983  0.7458118   0.          0.        ]
 [-1.24169843 -1.45395993 -0.8664597   0.          0.        ]
 [-1.0

## Sub-Matrices

In [20]:
sub_mat1=rand_mat1[0:2,0:3]
print(sub_mat1)
print('#-------------------------------break------------------------------------------------#')
sub_mat1[:]=3
print(sub_mat1)
print('#-------------------------------break------------------------------------------------#')
print(rand_mat1)

[[-1.62844806 -0.23799444  0.34990101]
 [ 2.69667929  0.57138983  0.7458118 ]]
#-------------------------------break------------------------------------------------#
[[3. 3. 3.]
 [3. 3. 3.]]
#-------------------------------break------------------------------------------------#
[[ 3.          3.          3.         -0.23961323 -0.4293945 ]
 [ 3.          3.          3.          0.          0.        ]
 [-1.24169843 -1.45395993 -0.8664597   0.          0.        ]
 [-1.07455972  1.01993955 -1.31048201  0.23128028 -0.20736838]
 [ 0.07021259  0.24831603  1.42263999  0.96738743  0.31780564]
 [-2.1004002   0.22979531  1.53062773  0.71230721  0.0422116 ]
 [-0.97583063  0.64105514 -0.21022044  0.52961954  0.8503158 ]
 [-1.44799996  1.0187636  -0.11990523  0.06173182  0.54310262]
 [-2.00163302 -0.30058876 -1.05312314  0.45041293 -0.59322718]
 [ 0.36024595 -0.54188599 -0.00347775  0.39264959 -0.36294193]]


In [21]:
sub_mat2=rand_mat1[0:2,0:3].copy()
sub_mat2[:]=99
print(sub_mat2)
print('#-------------------------------break------------------------------------------------#')
print(rand_mat1)

[[99. 99. 99.]
 [99. 99. 99.]]
#-------------------------------break------------------------------------------------#
[[ 3.          3.          3.         -0.23961323 -0.4293945 ]
 [ 3.          3.          3.          0.          0.        ]
 [-1.24169843 -1.45395993 -0.8664597   0.          0.        ]
 [-1.07455972  1.01993955 -1.31048201  0.23128028 -0.20736838]
 [ 0.07021259  0.24831603  1.42263999  0.96738743  0.31780564]
 [-2.1004002   0.22979531  1.53062773  0.71230721  0.0422116 ]
 [-0.97583063  0.64105514 -0.21022044  0.52961954  0.8503158 ]
 [-1.44799996  1.0187636  -0.11990523  0.06173182  0.54310262]
 [-2.00163302 -0.30058876 -1.05312314  0.45041293 -0.59322718]
 [ 0.36024595 -0.54188599 -0.00347775  0.39264959 -0.36294193]]


## Indexing using Logicals

In [22]:
rand_vec8=np.random.randn(15)
print('#-------------------------------break------------------------------------------------#')
print(rand_vec8)
print('#-------------------------------break------------------------------------------------#')
print(rand_vec8>0)
print('#-------------------------------break------------------------------------------------#')
print(rand_vec8[rand_vec8>0])
print('#-------------------------------break------------------------------------------------#')

#-------------------------------break------------------------------------------------#
[ 0.40218152  1.26426186 -0.73120182 -0.08959656  0.60177068 -0.76689581
 -1.64062481 -0.72661885  0.29327881  2.02760442 -0.53392734 -0.85708531
 -1.75301888  1.05073426 -0.60068274]
#-------------------------------break------------------------------------------------#
[ True  True False False  True False False False  True  True False False
 False  True False]
#-------------------------------break------------------------------------------------#
[0.40218152 1.26426186 0.60177068 0.29327881 2.02760442 1.05073426]
#-------------------------------break------------------------------------------------#


In [23]:
print(random_mat)
print('#-------------------------------break------------------------------------------------#')
print(random_mat>0)
print('#-------------------------------break------------------------------------------------#')
print(random_mat[random_mat>0])

[[0.98808995 0.88529284 0.72770628 0.48134232 0.60288724]
 [0.61035437 0.83916725 0.64739773 0.94330146 0.06638919]
 [0.2432535  0.45975662 0.38832284 0.6786458  0.89015808]
 [0.1046693  0.55070737 0.98901635 0.96135628 0.3349504 ]
 [0.29321803 0.52069268 0.81303998 0.91840361 0.98669848]]
#-------------------------------break------------------------------------------------#
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
#-------------------------------break------------------------------------------------#
[0.98808995 0.88529284 0.72770628 0.48134232 0.60288724 0.61035437
 0.83916725 0.64739773 0.94330146 0.06638919 0.2432535  0.45975662
 0.38832284 0.6786458  0.89015808 0.1046693  0.55070737 0.98901635
 0.96135628 0.3349504  0.29321803 0.52069268 0.81303998 0.91840361
 0.98669848]


In [24]:
print(rand_vec1)
print('#-------------------------------break------------------------------------------------#')
rand_vec1[rand_vec1>0.5]=-5
print(rand_vec1)

[ 2.24249213  1.25892355 -1.3739998   1.          2.          0.19455146
 -1.06580306 -1.47127565 -0.27287145  0.24278876 -1.02221927 -0.34232022
 -1.22974044 -0.1367791  -0.82647291 -1.66154358  0.07160188 -0.44131776
 -1.19638482]
#-------------------------------break------------------------------------------------#
[-5.         -5.         -1.3739998  -5.         -5.          0.19455146
 -1.06580306 -1.47127565 -0.27287145  0.24278876 -1.02221927 -0.34232022
 -1.22974044 -0.1367791  -0.82647291 -1.66154358  0.07160188 -0.44131776
 -1.19638482]


## Numpy array saving

In [25]:
np.save('numpy_array',random_mat)

In [26]:
np.savez('numpy_array_zip',rand_mat=rand_mat1,rand_mat2=random_mat)

In [27]:
loaded_vec=np.load('numpy_array.npy')
loaded_zip=np.load('numpy_array_zip.npz')
print('#-------------------------------break------------------------------------------------#')
print(loaded_vec)
print('#-------------------------------break------------------------------------------------#')
print(loaded_zip)
print('#-------------------------------break------------------------------------------------#')
print(loaded_zip['rand_mat'])
print('#-------------------------------break------------------------------------------------#')
print(loaded_zip['rand_mat2'])

#-------------------------------break------------------------------------------------#
[[0.98808995 0.88529284 0.72770628 0.48134232 0.60288724]
 [0.61035437 0.83916725 0.64739773 0.94330146 0.06638919]
 [0.2432535  0.45975662 0.38832284 0.6786458  0.89015808]
 [0.1046693  0.55070737 0.98901635 0.96135628 0.3349504 ]
 [0.29321803 0.52069268 0.81303998 0.91840361 0.98669848]]
#-------------------------------break------------------------------------------------#
#-------------------------------break------------------------------------------------#
[[ 3.          3.          3.         -0.23961323 -0.4293945 ]
 [ 3.          3.          3.          0.          0.        ]
 [-1.24169843 -1.45395993 -0.8664597   0.          0.        ]
 [-1.07455972  1.01993955 -1.31048201  0.23128028 -0.20736838]
 [ 0.07021259  0.24831603  1.42263999  0.96738743  0.31780564]
 [-2.1004002   0.22979531  1.53062773  0.71230721  0.0422116 ]
 [-0.97583063  0.64105514 -0.21022044  0.52961954  0.8503158 ]
 [-1.44

In [28]:
np.savetxt('numpy_array_text_file.txt',rand_mat1,delimiter=',')
rand_mat_txt=np.loadtxt('numpy_array_text_file.txt',delimiter=',')
print(rand_mat1)
print('#-------------------------------break------------------------------------------------#')
print(rand_mat_txt)

[[ 3.          3.          3.         -0.23961323 -0.4293945 ]
 [ 3.          3.          3.          0.          0.        ]
 [-1.24169843 -1.45395993 -0.8664597   0.          0.        ]
 [-1.07455972  1.01993955 -1.31048201  0.23128028 -0.20736838]
 [ 0.07021259  0.24831603  1.42263999  0.96738743  0.31780564]
 [-2.1004002   0.22979531  1.53062773  0.71230721  0.0422116 ]
 [-0.97583063  0.64105514 -0.21022044  0.52961954  0.8503158 ]
 [-1.44799996  1.0187636  -0.11990523  0.06173182  0.54310262]
 [-2.00163302 -0.30058876 -1.05312314  0.45041293 -0.59322718]
 [ 0.36024595 -0.54188599 -0.00347775  0.39264959 -0.36294193]]
#-------------------------------break------------------------------------------------#
[[ 3.          3.          3.         -0.23961323 -0.4293945 ]
 [ 3.          3.          3.          0.          0.        ]
 [-1.24169843 -1.45395993 -0.8664597   0.          0.        ]
 [-1.07455972  1.01993955 -1.31048201  0.23128028 -0.20736838]
 [ 0.07021259  0.24831603  1.4